// Generated by `cd engine && uv run intake schema --ts`. Do not edit by hand.

export interface Agent {
  npn: string;
  first_name: string;
  last_name: string;
  email: string | null;
  license_states: string[];
  upline_npn: string | null;
  status: AgentStatus;
  lineage: Lineage;
}

export type AgentStatus = "ACTIVE" | "INACTIVE" | "UNKNOWN";

export interface Client {
  client_id: string;
  first_name: string;
  last_name: string;
  dob: string;
  phone: string | null;
  email: string | null;
  address_line1: string;
  city: string;
  state: string;
  zip: string;
  mbi: string | null;
  household_id: string | null;
  notes: string | null;
  lineage: Lineage;
}

export interface CommissionLine {
  carrier: string;
  statement_period: string;
  line_no: number;
  carrier_member_id: string | null;
  member_name: string | null;
  member_dob: string | null;
  policy_ref: string | null;
  agent_npn: string | null;
  amount: string;
  commission_type: CommissionType;
  paid_date: string | null;
  lineage: Lineage;
}

export type CommissionType = "NEW" | "RENEWAL" | "OVERRIDE" | "CHARGEBACK";

export interface DetectionClass {
  defect_class: string;
  scored: boolean;
  planted: number;
  detected: number;
}

export interface DetectionSummary {
  classes: DetectionClass[];
  clean_rows: number;
  false_positive_rows: number;
  false_positive_rate: number;
}

export type EligibilityReason = "AGE" | "DISABILITY" | "ESRD";

export interface ExceptionRecord {
  id: string;
  rule_id: string;
  severity: Severity;
  family: Family;
  source: string;
  row_number: number | null;
  raw_hash: string | null;
  field: string | null;
  value_minimized: string | null;
  message: string;
  suggested_fix: string | null;
  blocks_load: boolean;
  lane: Lane;
  jev: JevScores | null;
  lineage: Lineage | null;
}

export type Family = "ING" | "MAP" | "SSN" | "CMP" | "DOB" | "MBI" | "NPN" | "PLN" | "ADR" | "CON" | "DAT" | "STA" | "DUP" | "REF" | "RTS" | "LIC" | "TIE" | "PII";

export interface Household {
  household_id: string;
  primary_client_id: string;
  members: string[];
  lineage: Lineage;
}

export interface InputFile {
  source: string;
  file_name: string;
  sha256: string;
  rows_expected: number | null;
  rows_received: number;
}

export type JevMode = "replay" | "off" | "live" | "record";

export interface JevScores {
  entry_error_probability: number | null;
  impact_score: number | null;
  pii_probability: number | null;
}

export interface JevUsage {
  mode: JevMode;
  calls: number;
  input_tokens: number;
  output_tokens: number;
  estimated_cost_usd: string;
  invalid_answers: number;
}

export type Lane = "SUGGESTED_FIX" | "REVIEW" | "BUSINESS_EVENT" | "UNREVIEWED";

export interface LegResult {
  leg: TieOutLeg;
  status: LegStatus;
  not_run_reason: string | null;
  matched: number | null;
  unmatched: number | null;
  weak_matched: number | null;
  variance_count: number | null;
  variance_dollars: string | null;
  variances: Variance[];
}

export type LegStatus = "RAN" | "NOT_RUN";

export interface LegSummary {
  leg: TieOutLeg;
  status: LegStatus;
  not_run_reason: string | null;
  matched: number | null;
  unmatched: number | null;
  weak_matched: number | null;
  variance_count: number | null;
  variance_dollars: string | null;
}

export type LineOfBusiness = "MA" | "PDP" | "MEDSUPP" | "ACA";

export interface Lineage {
  source_file: string;
  sheet: string | null;
  row_number: number;
  raw_hash: string;
  run_id: string;
  mapping_version: string;
}

export interface Manifest {
  run_id: string;
  started_at: string;
  finished_at: string;
  as_of: string | null;
  engine_version: string;
  status: RunStatus;
  status_reason: string | null;
  inputs: InputFile[];
  jev: JevUsage;
  budget_tripped: boolean;
  thresholds: Record<string, number>;
}

export interface MappingDecision {
  item_id: string;
  source: string;
  header: string;
  format_fingerprint: string;
  action: "approve" | "correct" | "ignore";
  field: string | null;
}

export interface MappingDecisions {
  run_id: string;
  mapping_version: string;
  reviewer: string;
  decided_at: string;
  note: "a reviewer's note, not an authenticated approval";
  decisions: MappingDecision[];
}

export interface MappingReview {
  run_id: string;
  mapping_version: string;
  jev_mode: JevMode;
  items: MappingReviewItem[];
}

export interface MappingReviewItem {
  item_id: string;
  source: string;
  file_name: string;
  header: string;
  format_fingerprint: string;
  samples: string[];
  samples_withheld: boolean;
  allowed_fields: string[];
  proposed_field: string | null;
  origin: "jev_replay" | "jev_live" | "jev_record" | "none";
  confidence: number | null;
  route: "auto" | "suggest" | "unmapped" | "person";
  reason: string | null;
  rows_with_value: number;
  exception_ids: string[];
  explanation: string;
}

export interface Policy {
  policy_id: string;
  client_id: string;
  carrier: string;
  plan_id: string;
  line_of_business: LineOfBusiness;
  state: string | null;
  eligibility_reason: EligibilityReason | null;
  effective_date: string;
  termination_date: string | null;
  status: PolicyStatus;
  writing_agent_npn: string;
  monthly_premium: string | null;
  carrier_member_id: string | null;
  lineage: Lineage;
}

export type PolicyStatus = "ACTIVE" | "PENDING" | "TERMINATED" | "CANCELLED" | "UNKNOWN";

export interface Rts {
  npn: string;
  carrier: string;
  state: string;
  plan_year: number;
  line_of_business: LineOfBusiness;
  appointed: boolean;
  certified: boolean;
  effective_date: string;
  end_date: string | null;
  lineage: Lineage;
}

export interface RtsCell {
  npn: string;
  carrier: string;
  state: string;
  plan_year: number;
  coverage: RtsCellState;
  policy_count: number;
  exception_ids: string[];
}

export type RtsCellState = "HELD_AND_USED" | "HELD_UNUSED" | "USED_WITHOUT_RTS";

export interface RtsCoverage {
  cells: RtsCell[];
}

export type RunStatus = "PASSED" | "PASSED_WITH_WARNINGS" | "FAILED";

export interface Scorecard {
  run_id: string;
  status: RunStatus;
  rows_in: number;
  rows_mapped: number;
  rows_clean: number;
  exceptions_by_severity: SeverityCounts;
  exceptions_by_rule: Record<string, number>;
  tie_out: LegSummary[];
  rts_gaps: number;
  detection: DetectionSummary | null;
}

export type Severity = "BLOCKER" | "ERROR" | "WARNING" | "INFO";

export interface SeverityCounts {
  blocker: number;
  error: number;
  warning: number;
  info: number;
}

export type TieOutLeg = "BOOK_VS_STATEMENT" | "STATEMENT_VS_BOOK" | "CRM_VS_STATEMENT";

export interface TotalRow {
  key: string;
  book_expected: string;
  statement_paid: string;
  difference: string;
  unexplained_revenue: string;
  within_tolerance: boolean;
}

export interface Totals {
  group_by: "carrier" | "agent";
  status: LegStatus;
  not_run_reason: string | null;
  rows: TotalRow[];
}

export interface Variance {
  rule_id: "TIE-001" | "TIE-002" | "TIE-003" | "TIE-004" | "TIE-005";
  exception_id: string;
  leg: TieOutLeg | null;
  carrier: string | null;
  statement_period: string | null;
  line_no: number | null;
  policy_id: string | null;
  carrier_member_id: string | null;
  agent_npn: string | null;
  paid: string | null;
  expected: string | null;
  difference: string;
}

export interface VarianceReport {
  variances: Variance[];
}
