"""TypeScript types for the dashboard, generated from the serialization JSON Schema.

Covers only the shapes this schema uses: objects, string enums, literals, arrays, maps,
nullable fields, and $ref. Anything else raises, so a new shape cannot slip through as `any`.
Money and dates arrive as strings, exactly as the run files store them.
"""

import json
from typing import Any

import agency_schema

HEADER = "// Generated by `cd engine && uv run intake schema --ts`. Do not edit by hand.\n"
SCALARS = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}


def _type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return str(node["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in node:
        return " | ".join(_type(option) for option in node["anyOf"])
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    kind = node.get("type")
    if kind == "null":
        return "null"
    if kind in SCALARS:
        return SCALARS[kind]
    if kind == "array":
        item = _type(node["items"])
        return f"({item})[]" if " | " in item else f"{item}[]"
    if kind == "object" and "properties" not in node:
        values = node.get("additionalProperties") or next(
            iter(node.get("patternProperties", {}).values()), None
        )
        if isinstance(values, dict):
            return f"Record<string, {_type(values)}>"
    raise ValueError(f"no TypeScript mapping for schema node {node}")


def _definition(name: str, node: dict[str, Any]) -> str:
    if "enum" in node:
        return f"export type {name} = {_type(node)};\n"
    lines = [f"export interface {name} {{"]
    for field, prop in node["properties"].items():
        if field not in node["required"]:
            raise ValueError(f"{name}.{field} has a default; schema fields must be required")
        lines.append(f"  {field}: {_type(prop)};")
    return "\n".join([*lines, "}"]) + "\n"


def render_typescript() -> str:
    defs = agency_schema.json_schema("serialization")["$defs"]
    body = "\n".join(_definition(name, defs[name]) for name in sorted(defs))
    return f"{HEADER}\n{body}"
