"""Guess how a file was written: encoding, delimiter, header row, and trailing total rows."""

import csv
import io
import re
from collections import Counter
from collections.abc import Sequence
from dataclasses import dataclass

from intake.config import (
    FOOTER_MAX_FILLED_CELLS,
    HEADER_MIN_TEXT_SHARE,
    HEADER_SCAN_ROWS,
    READER_DELIMITERS,
    READER_ENCODINGS,
    SNIFF_SAMPLE_LINES,
    TOTAL_ROW_PATTERN,
)

UTF8_BOM = b"\xef\xbb\xbf"
_NUMBER = re.compile(r"^[-+$]?[\d,]*\.?\d+%?$")
_TOTAL = re.compile(TOTAL_ROW_PATTERN)


def decode(data: bytes) -> tuple[str, str]:
    """Return (text, encoding name). A UTF-8 byte order mark is stripped but not trusted.

    Some exports write the UTF-8 marker and then latin-1 text, so the body is decoded on its
    own: each READER_ENCODINGS entry is tried strictly, in order, and the last one never fails.
    """
    body = data.removeprefix(UTF8_BOM)
    for encoding in READER_ENCODINGS[:-1]:
        try:
            return body.decode(encoding), encoding
        except UnicodeDecodeError:
            continue
    return body.decode(READER_ENCODINGS[-1]), READER_ENCODINGS[-1]


@dataclass(frozen=True)
class DelimiterGuess:
    delimiter: str
    confident: bool


def sniff_delimiter(text: str) -> DelimiterGuess:
    """Pick the delimiter that splits the first lines into the same number of fields.

    Each candidate is scored by how many sample lines share its most common field count (at
    least two fields). The guess is confident when every sample line agrees.
    """
    lines = [line for line in text.splitlines()[:SNIFF_SAMPLE_LINES] if line.strip()]
    best: tuple[float, int, str] | None = None
    for delim in READER_DELIMITERS:
        counts = [len(row) for row in csv.reader(lines, delimiter=delim)]
        if not counts:
            continue
        width, hits = Counter(counts).most_common(1)[0]
        if width < 2:
            continue
        score = (hits / len(counts), width, delim)
        if best is None or score[:2] > best[:2]:
            best = score
    if best is None:
        return DelimiterGuess(READER_DELIMITERS[0], confident=False)
    return DelimiterGuess(best[2], confident=best[0] == 1.0)


def split_rows(text: str, delimiter: str) -> list[list[str]]:
    return list(csv.reader(io.StringIO(text, newline=""), delimiter=delimiter))


def _is_text(cell: object) -> bool:
    return isinstance(cell, str) and cell.strip() != "" and not _NUMBER.match(cell.strip())


def find_header_row(rows: Sequence[Sequence[object]]) -> int:
    """0-based index of the first row whose cells are mostly words, past any title rows.

    A merged title row has one filled cell out of many, so it fails the HEADER_MIN_TEXT_SHARE
    test against the widest row. Falls back to the first row when nothing qualifies.
    """
    scan = rows[:HEADER_SCAN_ROWS]
    width = max((len(r) for r in scan), default=0)
    for i, row in enumerate(scan):
        if width and sum(_is_text(c) for c in row) / width >= HEADER_MIN_TEXT_SHARE:
            return i
    return 0


def _filled(row: Sequence[str | None]) -> int:
    return sum(1 for c in row if c is not None and str(c).strip() != "")


def is_total_row(row: Sequence[str | None]) -> bool:
    """True when the first cell reads total, totals, grand total, or subtotal (any case)."""
    first = " ".join(str(row[0] or "").lower().split()) if row else ""
    return bool(_TOTAL.match(first))


def count_trailers(rows: Sequence[Sequence[str | None]]) -> int:
    """How many rows at the end form the trailing total block, found by content.

    The block starts at the first total row whose following rows are all totals, blanks, or
    footer notes (a row with at most FOOTER_MAX_FILLED_CELLS filled cells, such as
    "Generated by CarrierPortal" or "Page 1 of 2"). With no total row, only trailing blank
    rows are dropped, so a sparse last row is never thrown away on its own.
    """
    n = len(rows)
    start = n
    block_start: int | None = None
    while start > 0:
        row = rows[start - 1]
        if is_total_row(row):
            block_start = start - 1
        elif _filled(row) > FOOTER_MAX_FILLED_CELLS:
            break
        start -= 1
    if block_start is not None:
        return n - block_start
    blanks = 0
    while blanks < n and _filled(rows[n - 1 - blanks]) == 0:
        blanks += 1
    return blanks


def total_row_count(rows: Sequence[Sequence[str | None]]) -> int | None:
    """The data row count a total row prints in its second cell, when it prints one."""
    for row in rows:
        if is_total_row(row) and len(row) > 1 and (row[1] or "").strip().isdigit():
            return int((row[1] or "").strip())
    return None
